using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Audio;

public class PlaySounds : MonoBehaviour
{
    public AudioSource [] sound;

    void Update()
    {
        //w>z
        if (Input.GetKeyDown(KeyCode.Z) )
        {
            sound[25].Play();
            //mission
            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            
        }
        //a>q
        if (Input.GetKeyDown(KeyCode.Q))
        {
            sound[2].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.S))
        {
            sound[3].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.D))
        {
            sound[4].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.F))
        {
            sound[5].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.G))
        {
            sound[6].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.Space))
        {
            sound[7].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.UpArrow))
        {
            sound[8].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.RightArrow))
        {
            sound[9].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.DownArrow))
        {
            sound[10].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.LeftArrow))
        {
            sound[11].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.Mouse0))
        {
            sound[12].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }

        if (Input.GetKeyDown(KeyCode.Q) && Input.GetKeyDown(KeyCode.Z) )
        {
            sound[13].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.S) && Input.GetKeyDown(KeyCode.D))
        {
            sound[14].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.F) && Input.GetKeyDown(KeyCode.G))
        {
            sound[15].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.Space) && Input.GetKeyDown(KeyCode.Mouse0))
        {
            sound[16].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.UpArrow) && Input.GetKeyDown(KeyCode.DownArrow))
        {
            sound[17].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.LeftArrow) && Input.GetKeyDown(KeyCode.RightArrow))
        {
            sound[18].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.Z) && Input.GetKeyDown(KeyCode.LeftArrow))
        {
            sound[19].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.Q) && Input.GetKeyDown(KeyCode.DownArrow))
        {
            sound[20].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.S) && Input.GetKeyDown(KeyCode.RightArrow))
        {
            sound[21].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.D) && Input.GetKeyDown(KeyCode.UpArrow))
        {
            sound[22].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.S) && Input.GetKeyDown(KeyCode.D))
        {
            sound[23].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.F) && Input.GetKeyDown(KeyCode.Mouse0))
        {
            sound[24].Play();

            sound[0].Stop();
            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.F) && Input.GetKeyDown(KeyCode.Q))
        {
            sound[1].Play();

            sound[0].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
        if (Input.GetKeyDown(KeyCode.G) && Input.GetKeyDown(KeyCode.Space))
        {
            sound[0].Play();

            sound[1].Stop();
            sound[2].Stop();
            sound[3].Stop();
            sound[4].Stop();
            sound[5].Stop();
            sound[6].Stop();
            sound[7].Stop();
            sound[8].Stop();
            sound[9].Stop();
            sound[10].Stop();
            sound[11].Stop();
            sound[12].Stop();
            sound[13].Stop();
            sound[14].Stop();
            sound[15].Stop();
            sound[16].Stop();
            sound[17].Stop();
            sound[18].Stop();
            sound[19].Stop();
            sound[20].Stop();
            sound[21].Stop();
            sound[22].Stop();
            sound[23].Stop();
            sound[24].Stop();
            sound[25].Stop();
        }
    }
}
